### ISSUE TITLE
Update File Upload server

### ISSUE THREAD

**Issue by meladawy** [EMBL-EBI-SUBS/data-submissions-interface#1]
https://github.com/EMBL-EBI-SUBS/data-submissions-interface/blob/e5c17963cd39984d42c2013b3b42b7153392681d/src/app/pages/submission-pages/data-page/data-page.component.ts#L30

We can use one of the following : 
wp-p1m-5f    7.8 GB    4    file-upload-service    DEV
wp-p1m-58    7.8 GB    4    file-upload-service    TEST
wp-p1m-59    7.8 GB    4    file-upload-service    TEST
wp-p1m-5c    7.8 GB    4    file-upload-service    PROD
wp-p1m-5d    7.8 GB    4    file-upload-service    PROD
wp-p1m-5e    7.8 GB    4    file-upload-service    PROD

**Comment by meladawy** [comment]
http://wp-p1m-58.ebi.ac.uk:1080/files/

**Comment by davidrichardson** [comment]
The UI should not need to know the internal server names.

We’ve added a link to the API root that should give the appropriate upload endpoint.

https://submission-dev.ebi.ac.uk/api <https://submission-dev.ebi.ac.uk/api/browser/index.html#/api/> -> _links -> tus_upload

The values are currently…

dev https://submission-dev.ebi.ac.uk/files/
test https://submission-test.ebi.ac.uk/files/
prod https://submission.ebi.ac.uk/files/
